apiVersion: v1
kind: Service
metadata:
  name: coredns
  namespace: kube-system
  labels:
    application: kubernetes
    component: coredns
spec:
  selector:
    component: coredns
  clusterIP: 10.5.0.11
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
