apiVersion: v1
kind: Secret
metadata:
  name: karpenter-cert
  namespace: kube-system
  labels:
    application: kubernetes
    component: karpenter
type: Opaque
data: {} # Injected by karpenter-webook
