apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    application: kubernetes
    component: metrics-server
spec:
  selector:
    application: kubernetes
    component: metrics-server
  ports:
  - port: 443
    protocol: TCP
    targetPort: 4443
