{{ $version := "master-101" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-gateway-controller
  namespace: kube-system
  labels:
    application: gateway-operator
    component: fabric-gateway-controller
    version: {{ $version }}
spec:
{{ if eq .ConfigItems.fabric_gateway_controller_mode "disabled" }}
  replicas: 0
{{ else }}
  replicas: 1
{{ end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      deployment: fabric-gateway-controller
  template:
    metadata:
      labels:
        deployment: fabric-gateway-controller
        application: gateway-operator
        component: fabric-gateway-controller
        version: {{ $version }}
      annotations:
        logging/destination: "{{ .Cluster.ConfigItems.log_destination_infra }}"
        prometheus.io/path: /metrics
        prometheus.io/port: "7979"
        prometheus.io/scrape: "true"
    spec:
      priorityClassName: "{{ .Cluster.ConfigItems.system_priority_class }}"
      serviceAccountName: fabric-gateway-controller
      containers:
        - name: controller
          image: container-registry.zalando.net/gwproxy/fabric-gateway:{{ $version }}
          args:
{{ if eq .ConfigItems.fabric_gateway_controller_mode "production" }}
            - -predicates=True() && True()
            - -update-fabric-gateway-status=true
{{ else }}
            - -predicates=False()
            - -update-fabric-gateway-status=false
{{ end }}
            - -filters=setRequestHeader("X-Route-Controller", "fabric-gateway-controller")
            - -log-level=info
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              memory: 1Gi
