kind: Service
apiVersion: v1
metadata:
  name: node-monitor
  namespace: kube-system
  labels:
    application: node-monitor
spec:
  type: ClusterIP
  ports:
{{- if eq .Cluster.ConfigItems.cadvisor_enabled "true" }}
    - name: cadvisor
      port: 80
      targetPort: 9101
      protocol: TCP
{{- end }}
    - name: node-exporter
      port: 81
      targetPort: 9100
      protocol: TCP
  selector:
    application: kubernetes
    component: node-monitor
