{{ if eq .ConfigItems.spot_node_rescheduler "true" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: node-spot-rescheduler
  namespace: kube-system
  labels:
    application: kubernetes
    component: node-spot-rescheduler
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      backoffLimit: 1
      template:
        metadata:
          labels:
            application: kubernetes
            component: node-spot-rescheduler
        spec:
          serviceAccountName: node-spot-rescheduler
          restartPolicy: Never
          containers:
          - name: node-spot-rescheduler
            image: container-registry.zalando.net/teapot/spot-node-rescheduler:main-1
            resources:
            limits:
              cpu: "{{ .ConfigItems.spot_node_rescheduler_cpu }}"
              memory: "{{ .ConfigItems.spot_node_rescheduler_memory }}"
            requests:
              cpu: "{{ .ConfigItems.spot_node_rescheduler_cpu }}"
              memory: "{{ .ConfigItems.spot_node_rescheduler_memory }}"
{{ end }}
