apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: event-logger-vpa
  namespace: kube-system
  labels:
    application: kubernetes
    component: event-logger
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: kubernetes-event-logger
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
    - containerName: logger
      minAllowed:
        memory: {{.Cluster.ConfigItems.event_logger_mem_min}}
        cpu: {{.Cluster.ConfigItems.event_logger_cpu_min}}
