Metadata:
  StackName: "kubernetes-on-aws-deploy-event-{{{CDP_TARGET_BRANCH}}}"
  Tags:
    application: "kubernetes"
    component: "deploy-event"

AWSTemplateFormatVersion: "2010-09-09"
Description: "Empty stack to emit deploy event"

Conditions:
  Never:
    !Equals [ "A", "B" ]

Resources:
  NonResource:
    Type: Custom::NonResource
    Condition: Never
