{{ $min_replicas := .Cluster.ConfigItems.skipper_ingress_min_replicas }}
{{ if and
  (eq .Cluster.ConfigItems.skipper_ingress_canary_enabled "true")
  (ne .Cluster.ConfigItems.skipper_ingress_min_replicas "0")
  (ne .Cluster.ConfigItems.skipper_ingress_min_replicas "1") }}
{{ $min_replicas = sumQuantities .Cluster.ConfigItems.skipper_ingress_min_replicas "-1" }}
{{ end }}

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skipper-ingress
  namespace: kube-system
  labels:
    application: skipper-ingress
    component: ingress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skipper-ingress
  minReplicas: {{ $min_replicas }}
  maxReplicas: {{ .Cluster.ConfigItems.skipper_ingress_max_replicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Cluster.ConfigItems.skipper_ingress_target_average_utilization_cpu }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Cluster.ConfigItems.skipper_ingress_target_average_utilization_memory }}
{{ if .Cluster.ConfigItems.skipper_cluster_scaling_schedules }}
  {{ range split .Cluster.ConfigItems.skipper_cluster_scaling_schedules "," }}
  {{ $name_target := split . "=" }}
  - type: Object
    object:
      describedObject:
        apiVersion: zalando.org/v1
        kind: ClusterScalingSchedule
        name: {{ index $name_target 0 }}
      metric:
        name: {{ index $name_target 0 }}
      target:
        averageValue: {{ index $name_target 1 }}
        type: AverageValue
  {{ end }}
{{ end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Cluster.ConfigItems.skipper_ingress_hpa_scale_down_wait }}
      policies:
      - type: Pods
        value: 10
        periodSeconds: 60
      - type: Percent
        value: 100
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 4
      - periodSeconds: 15
        type: Percent
        value: {{ .Cluster.ConfigItems.skipper_ingress_hpa_scale_up_max_perc }}
      selectPolicy: Max
      stabilizationWindowSeconds: 0
