{{ if eq .Cluster.ConfigItems.skipper_oauth2_ui_login "true" }}
apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
  name: skipper-ingress-platform-credentials
  namespace: kube-system
  labels:
    application: skipper-ingress
spec:
  application: skipper-ingress
  token_version: v2
  clients:
    {{ .Cluster.Alias }}-employee:
      grant: authorization-code
      realm: users
      redirectUri: "https://{{ .ConfigItems.skipper_oauth2_redirect_uri_host }}{{ .ConfigItems.skipper_oauth2_redirect_uri_path }}"

{{ if ne .ConfigItems.skipper_oauth2_ui_login_hostnames "" }}

{{ $redirect_uri_path := .ConfigItems.skipper_oauth2_redirect_uri_path }}
{{ $config_hash := printf "%.32s" (.ConfigItems.skipper_oauth2_ui_login_hostnames | sha256) }}

{{ range split .ConfigItems.skipper_oauth2_ui_login_hostnames "," }}
{{ $hostname := index (split . "=") 0 }}
{{ $application := index (split . "=") 1 }}
---
apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
  name: "{{ $hostname }}-credentials"
  namespace: kube-system
  labels:
    application: skipper-ingress
    component: hostname-credentials
    config-hash: {{ $config_hash }}
spec:
  application: "{{ $application }}"
  token_version: v2
  clients:
    {{ $hostname }}-employee:
      grant: authorization-code
      realm: users
      redirectUri: "https://{{ $hostname }}{{ $redirect_uri_path }}"
{{ end }}
{{ end }}

{{ end }}
