apiVersion: zalando.org/v1
kind: RouteGroup
metadata:
  name: synthetic-probe
  namespace: kube-system
spec:
  backends:
  - name: simulation
    type: shunt
  defaultBackends:
  - backendName: simulation
  hosts:
  - cluster-health.{{ .Cluster.Alias }}.zalan.do
  routes:
  - pathSubtree: /
    filters:
    - disableAccessLog()
    - inlineContent("OK")
