kind: Service
apiVersion: v1
metadata:
  name: skipper-internal
  namespace: kube-system
  labels:
    application: skipper-ingress
    component: ingress
spec:
  type: ClusterIP
  clusterIP: 10.5.99.99
  ports:
    - port: 80
      targetPort: 9999
      protocol: TCP
{{if eq .Cluster.ConfigItems.skipper_ingress_eastwest_additional_port "true"}}
    - port: 8080
      targetPort: 9999
      protocol: TCP
{{end}}
  selector:
    application: skipper-ingress
    component: ingress
