{{- if or .Cluster.ConfigItems.audittrail_url .Cluster.ConfigItems.audittrail_nakadi_url }}
apiVersion: "zalando.org/v1"
kind: PlatformCredentialsSet
metadata:
   name: "audittrail-adapter"
   namespace: kube-system
   labels:
     application: "audittrail-adapter"
spec:
   application: "audittrail-adapter"
   token_version: v2
   tokens:
{{- end }}
{{- if .Cluster.ConfigItems.audittrail_url }}
     audittrail:
       privileges: []
{{- end }}
{{- if .Cluster.ConfigItems.audittrail_nakadi_url }}
     nakadi:
       privileges:
       - com.zalando::nakadi.event_stream.write
{{- end }}
