# based on:
#
#   https://github.com/NVIDIA/k8s-device-plugin/blob/master/nvidia-device-plugin.yml
#
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-gpu-device-plugin
  namespace: kube-system
  labels:
    application: kubernetes
    component: nvidia-gpu-device-plugin
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      daemonset: nvidia-gpu-device-plugin
  template:
    metadata:
      labels:
        daemonset: nvidia-gpu-device-plugin
        application: kubernetes
        component: nvidia-gpu-device-plugin
      annotations:
        logging/destination: "{{.Cluster.ConfigItems.log_destination_infra}}"
    spec:
      serviceAccountName: nvidia
      tolerations:
      - operator: Exists
        effect: NoExecute
      - operator: Exists
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zalando.org/nvidia-gpu
                operator: Exists
            - matchExpressions:
              - key: karpenter.k8s.aws/instance-gpu-manufacturer
                operator: In
                values:
                - nvidia
      priorityClassName: system-node-critical
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      containers:
      - name: nvidia-gpu-device-plugin
        image: container-registry.zalando.net/teapot/nvidia-gpu-device-plugin:v0.14.4-master-9
        args:
        - --fail-on-init-error=false
        - --pass-device-specs
        resources:
          requests:
            cpu: "{{ .Cluster.ConfigItems.nvidia_device_plugin_cpu }}"
            memory: "{{ .Cluster.ConfigItems.nvidia_device_plugin_memory }}"
          limits:
            cpu: "{{ .Cluster.ConfigItems.nvidia_device_plugin_cpu }}"
            memory: "{{ .Cluster.ConfigItems.nvidia_device_plugin_memory }}"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
